//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var shared_ttypes = require('./shared_types');


var ttypes = require('./tutorial_types');
//HELPER FUNCTIONS AND STRUCTURES

var zkDataService_zkData_args = function(args) {
};
zkDataService_zkData_args.prototype = {};
zkDataService_zkData_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

zkDataService_zkData_args.prototype.write = function(output) {
  output.writeStructBegin('zkDataService_zkData_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var zkDataService_zkData_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
zkDataService_zkData_result.prototype = {};
zkDataService_zkData_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

zkDataService_zkData_result.prototype.write = function(output) {
  output.writeStructBegin('zkDataService_zkData_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var zkDataServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
zkDataServiceClient.prototype = {};
zkDataServiceClient.prototype.seqid = function() { return this._seqid; };
zkDataServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
zkDataServiceClient.prototype.zkData = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_zkData();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_zkData();
  }
};

zkDataServiceClient.prototype.send_zkData = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('zkData', Thrift.MessageType.CALL, this.seqid());
  var args = new zkDataService_zkData_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

zkDataServiceClient.prototype.recv_zkData = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new zkDataService_zkData_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('zkData failed: unknown result');
};
var zkDataServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
zkDataServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
zkDataServiceProcessor.prototype.process_zkData = function(seqid, input, output) {
  var args = new zkDataService_zkData_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.zkData.length === 0) {
    Q.fcall(this._handler.zkData.bind(this._handler))
      .then(function(result) {
        var result_obj = new zkDataService_zkData_result({success: result});
        output.writeMessageBegin("zkData", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("zkData", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.zkData(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new zkDataService_zkData_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("zkData", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("zkData", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
